### ISSUE TITLE
NICE FloR-S 52bit

### ISSUE THREAD

**Issue by nocomp** [tobiabocchi/flipperzero-bruteforce#1]
HI
thx for the repo, my nice keyfob is declared as NICE FloR-S 52bit using "Read" function.
What directory should i take in /nice/ folder in order to replay an attack?
best regards

**Comment by tobiabocchi** [comment]
Hello, if the remote uses a 52bit code then a brute force attack is probably unfeasible since it would take too long to execute. The NICE protocol used in my script is a 12 bit protocol, so not the same one of your remote
