### ISSUE TITLE
Request GateTX Protocol Implementation

### ISSUE THREAD

**Issue by Blizire** [tobiabocchi/flipperzero-bruteforce#11]
I am requesting information/links on how you found the protocol information for CAME. I would like to to implement GateTX protocol to contribute to your repo.

My specific goal is to produce a sub file to brute force the breezehome fan/light remote (or the protocol) since I have a few in my place and see it as a decent project to learn more about the flipper and producing more code for it.

What I want to know is how you found the information for:
trasposition table,
pilot period,
stop bit

GATETX INFO
Frequency: 433920000
Preset: FuriHalSubGhzPresetOok650Async
Protocol: GateTX
Bit: 24

Attached are example subfiles for raw and captured GateTX versions that are working.
[examples.zip](https://github.com/tobiabocchi/flipperzero-bruteforce/files/9742699/examples.zip)

**Comment by tobiabocchi** [comment]
Hello, thank you for providing the files, 24 bits have too many combinations to make bruteforcing feasible.. It would take too long (days if not weeks) to send all the codes.. That is why in this repo I only keep track of protocols with less then ~15 bits. If you really wanted to you could add the protocol to the python script, to figure out the parameters of the protocol you can either look into the firmware's source code or analyse the signal yourself using [this tool](https://my.flipp.dev/pulse-plotter)
