### ISSUE TITLE
Hi i have a request

### ISSUE THREAD

**Issue by Mannybaklanov** [tobiabocchi/flipperzero-bruteforce#2]
Hi by any chance would it be possible to give me a code or something to put in my flipper to act as an remote for a promethium board but with no remote like could u give me codes or something that would be able to do like on and off or something, thanks

**Comment by tobiabocchi** [comment]
Sorry you need to be more specific than this, what protocol are you trying to bruteforce? To provide a sub file I need to know long and short pulse length in microseconds, pilot period/end bit, etc...
