### ISSUE TITLE
Question about the Speed

### ISSUE THREAD

**Issue by KejuBartin** [tobiabocchi/flipperzero-bruteforce#20]
How fast do these Bruteforce attacks run? Do they use the De Bruijn Sequence?
This, of course only works with shift bit registers on the reciever side, but it would speed up the attack dramatically. If you don't know what im talking about, take a look at this Video from Veritasium: https://www.youtube.com/watch?v=CNodxp9Jy4A 
and this Video from Samy Kamkar: https://www.youtube.com/watch?v=iSSRaIU9_Vc 
If you could do the exact same thing with the Flipper Zero, it would be awesome.

**Comment by tobiabocchi** [comment]
Yes those are already present in the repo
