### ISSUE TITLE
868 MHz set

### ISSUE THREAD

**Issue by rct31** [tobiabocchi/flipperzero-bruteforce#3]
Is it possible to add a set of these key at the frequency of 868 MHz so it would cover a larger number of possibility ?

**Comment by tobiabocchi** [comment]
Yes of course, I will do that asap. What protocols have you seen using that frequency?

**Comment by rct31** [comment]
Cool ! In Camebruteforcer BitcoinRaven speaks about CAME gates with a 12 bits code at 868.35 MHz, that's why I'm asking that. 

I don't know if these gates exist in large number or not and if CAME is the only protocol in use in this frequency.

**Comment by tobiabocchi** [comment]
Added 868 CAME and NICE to sub files
