### ISSUE TITLE
CAME speed improvements dramatically decrease accuracy.

### ISSUE THREAD

**Issue by Astrrra** [tobiabocchi/flipperzero-bruteforce#4]
Hi! I've noticed that the timing changes in the CAME protocols seem to drastically decrease the attack's efficiency. You can check this for yourself if you have two flippers or any other SubGhz signal analyser. With the sped-up timings, only about 10% of the signals actually get detected, and the same behaviour can be observed on CAME barriers themselves. I think rolling those changes back to the ` {"0": "-320 640 ", "1": "-640 320 "}, "-11520 320 "` state is the best thing to do here. Even if it slows down the attack, all the benefits of that speed are lost if you have to re-run the file multiple times for the barrier to actually detect the matching signal.

**Comment by tobiabocchi** [comment]
Yes you are right, I made a new protocol named CAME-fast with the speed improvements, the standard protocol now is still in the sub_files
