### ISSUE TITLE
Add up to 24 bits to all types of protocols 

### ISSUE THREAD

**Issue by usmanovbf** [tobiabocchi/flipperzero-bruteforce#43]
Hi! It would definitely help us to match enhanced versions of protocols that use 24 bits. For instance, I face with came 24 bits every time in my life but I can not bruteforce it, only read existing and emulate then

**Comment by usmanovbf** [comment]
Hi! Is there any news?

**Comment by tobiabocchi** [comment]
This is not supported because brute forcing 24bit signals would take too long, maybe even months
