### ISSUE TITLE
Not a real issue

### ISSUE THREAD

**Issue by andrea-fabbro** [tobiabocchi/flipperzero-bruteforce#5]
Come dice il titolo, non è veramente un "issue", ma non saprei come altro "raggiungerti" (la tua mail non è pubblica).

Da Italiano, da ex atleta (amatoriale) di salto in lungo e salto triplo, e recentemente anche da utente di un flipper zero, volevo complimentarmi per i risultati sul campo di atletica e per il codice scritto (che ho trovato estremamente utile oltre che ben organizzato), due cose che possono sembrare poco conciliabili... ma che invece ci dimostri possono essere coltivate assieme.

BRAVO!

**Comment by tobiabocchi** [comment]
Grazie del supporto! Lo apprezzo moltissimo!
