### ISSUE TITLE
Gate question

### ISSUE THREAD

**Issue by marziuss** [tobiabocchi/flipperzero-bruteforce#9]
Dear tobiabacchi,
Thank you for the github code.
I’ve a question for you, will you implement the bruteforce also for Faac gates? I have my own Faac gate so, if I understood correctly, I cannot bruteforce it. It would be nice to have also those scripts for that gate. Thank u! Enjoy :)

**Comment by tobiabocchi** [comment]
Bruteforce is feasible for protocols using fixed code only, if your remote is rolling code it probably cannot be bruteforced. Do you have more info about the protocol it uses?

**Comment by marziuss** [comment]
> Bruteforce is feasible for protocols using fixed code only, if your remote is rolling code it probably cannot be bruteforced. Do you have more info about the protocol it uses?

I don't have more info about it, it shouldn't have the rolling code, it is a gate like CAME or others... I'm searching for a bruteforce code of that model gate but I can't find it. It would be nice to implement the script. Thank you for the reply!🙂

**Comment by tobiabocchi** [comment]
What does the flipper say when you try to record the signal from the remote? If it's not detected by flipper you can raw read it and share the .sub file to analyze

**Comment by marziuss** [comment]
> What does the flipper say when you try to record the signal from the remote? If it's not detected by flipper you can raw read it and share the .sub file to analyze

Ok, I'm new with this device so I will try to read and understand how to retrieve the .sub file from the signal.
Meanwhile, I tried to open a CAME of one friend to test your bruteforce code but it didn't work, I suppose because its gate is on 24bit (the read signal says 24bit), and the maximum that your code provide is 12bit, so I think this is the reason of failure, is it right? Will you implement also for 24bit? 
Thank you for your time 😀

**Comment by tobiabocchi** [comment]
Yes that is correct, if reading it from the flipper says it's 24 bits than it cannot be bruteforced using the subfiles of this repo.
